### PR TITLE
Added method to retrieve Coins OHLCV Historical

### PR DESCRIPTION
**Pull request by lucasfabre**
Hello,

I was using the package for a school project and I needed the Coins OHLCV Historical.
Thanks you for the free coinpaprika API.

### CODE REVIEW

**Comment by M4rcinJ** [comment]
Hi, it looks good beyond a small detail. `typeof []` will return the same output as `typeof {}` because of in JavaScript arrays are technically objects with special behaviours and abilities. Please solve that issue using comparison like this: ` Object.prototype.toString.call(obj) === '[object Object]'`  or duck typing and write more test cases.

**Comment by lucasfabre** [comment]
Hi, sorry for the late fix, I fixed the problem and added an associated test case.

**Comment by M4rcinJ** [comment]
Hi, thanks for fix that but I've noticed one more thing which may be improve. In case when you have to check if error has been thrown it is better to use dedicated method `.toThrowError` rather than throw new error and compare two strings https://jestjs.io/docs/en/expect#tothrowerror

**Comment by lucasfabre** [comment]
Is it better now ?

**Pull request merged**
